[application]

# App (Project) Name
name = "medium_leaderboard"

[web.app]

# HTML title tag content
title = "medium_leaderboard"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["https://cdnjs.cloudflare.com/ajax/libs/bulma/1.0.2/css/bulma.min.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
